# Generated by Django 4.2.3 on 2023-10-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_translate', '0009_remove_language_easyocr_remove_language_facebookm2m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbox',
            old_name='from_ocr',
            new_name='from_ocr_merged',
        ),
    ]
