# Generated by Django 4.2.3 on 2023-10-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_translate', '0010_rename_from_ocr_bbox_from_ocr_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbox',
            name='from_ocr_single',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_single', to='ocr_translate.ocrboxrun'),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='from_ocr_merged',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_merged', to='ocr_translate.ocrboxrun'),
        ),
    ]
