# Generated by Django 4.2.3 on 2023-10-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_translate', '0011_bbox_from_ocr_single_alter_bbox_from_ocr_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='ocr_mode',
            field=models.CharField(choices=[('single', 'Single'), ('merged', 'Merged')], default='merged', max_length=32),
        ),
    ]
