# Generated by Django 4.2.3 on 2023-10-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_translate', '0014_ocrrun_result_single_alter_ocrrun_result_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbox',
            name='to_merged',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_single', to='ocr_translate.bbox'),
        ),
    ]
