# Generated by Django 4.2.2 on 2023-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrboxmodel',
            name='languages',
            field=models.ManyToManyField(related_name='box_models', to='base.language'),
        ),
        migrations.AddField(
            model_name='ocrboxrun',
            name='lang_src',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='box_src', to='base.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocrboxrun',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_box', to='base.image'),
        ),
        migrations.AlterField(
            model_name='ocrrun',
            name='lang_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_src', to='base.language'),
        ),
        migrations.AlterField(
            model_name='translationrun',
            name='lang_dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_dst', to='base.language'),
        ),
        migrations.AlterField(
            model_name='translationrun',
            name='lang_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_src', to='base.language'),
        ),
    ]
