# Generated by Django 4.2.2 on 2023-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ocrboxmodel_languages_ocrboxrun_lang_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='easyocr',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
