# Generated by Django 4.2.2 on 2023-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_translationrun_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
