# Generated by Django 4.2.2 on 2023-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_language_easyocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='tesseract',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ocrboxmodel',
            name='language_format',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='language_format',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tslmodel',
            name='language_format',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
