# Generated by Django 4.2.2 on 2023-07-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_text_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tslmodel',
            name='dst_language',
        ),
        migrations.RemoveField(
            model_name='tslmodel',
            name='src_language',
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='languages',
            field=models.ManyToManyField(related_name='ocr_models', to='base.language'),
        ),
        migrations.AddField(
            model_name='translationrun',
            name='dst_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_trans', to='base.language'),
        ),
        migrations.AddField(
            model_name='translationrun',
            name='src_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_trans', to='base.language'),
        ),
        migrations.AddField(
            model_name='tslmodel',
            name='dst_languages',
            field=models.ManyToManyField(related_name='tsl_models_dst', to='base.language'),
        ),
        migrations.AddField(
            model_name='tslmodel',
            name='src_languages',
            field=models.ManyToManyField(related_name='tsl_models_src', to='base.language'),
        ),
        migrations.AlterField(
            model_name='text',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='base.language'),
        ),
    ]
