# Generated by Django 4.2.2 on 2023-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_language_tesseract_ocrboxmodel_language_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(unique=True)),
            ],
        ),
    ]
