# Generated by Django 4.2.2 on 2023-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_optiondict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrboxrun',
            name='options',
        ),
        migrations.RemoveField(
            model_name='ocrrun',
            name='options',
        ),
        migrations.RemoveField(
            model_name='translationrun',
            name='options',
        ),
    ]
