# Generated by Django 4.2.2 on 2023-07-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_language_remove_tslmodel_dst_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationrun',
            name='dst_lang',
        ),
        migrations.RemoveField(
            model_name='translationrun',
            name='src_lang',
        ),
    ]
