# Generated by Django 4.2.2 on 2023-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ocrboxrun_options_ocrrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='facebookM2M',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
