# Generated by Django 4.2.2 on 2023-07-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_language_facebookm2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrboxrun',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_runs', to='base.ocrboxmodel'),
        ),
        migrations.AlterField(
            model_name='ocrrun',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_runs', to='base.ocrmodel'),
        ),
        migrations.AlterField(
            model_name='translationrun',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tsl_runs', to='base.tslmodel'),
        ),
    ]
