# Generated by Django 4.2.2 on 2023-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_ocrboxrun_model_alter_ocrrun_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='break_chars',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='ignore_chars',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
