# Generated by Django 4.2.2 on 2023-07-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_language_break_chars_language_ignore_chars'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTranslationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_tsl_runs', to='base.tslmodel')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_trans_options', to='base.optiondict')),
                ('result', models.ManyToManyField(related_name='from_batch_trans', to='base.text')),
                ('text', models.ManyToManyField(related_name='to_batch_trans', to='base.text')),
            ],
        ),
        migrations.AddField(
            model_name='translationrun',
            name='from_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_equivalent', to='base.batchtranslationrun'),
        ),
    ]
