# Generated by Django 4.2.2 on 2023-07-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_batchtranslationrun_translationrun_from_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtranslationrun',
            name='lang_dst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_trans_dst', to='base.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchtranslationrun',
            name='lang_src',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_trans_src', to='base.language'),
            preserve_default=False,
        ),
    ]
