# Generated by Django 4.2.2 on 2023-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_batchtranslationrun_lang_dst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='easyocr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='facebookM2M',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso1',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso2b',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso2t',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='tesseract',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
