# Generated by Django 4.2.2 on 2023-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_name_language_iso1'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='iso2b',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='iso2t',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso1',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
