# Generated by Django 4.2.2 on 2023-07-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_language_easyocr_alter_language_facebookm2m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationrun',
            name='from_batch',
        ),
        migrations.DeleteModel(
            name='BatchTranslationRun',
        ),
    ]
