# Generated by Django 4.2.2 on 2023-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_language_iso2b_language_iso2t_language_iso3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso1',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso2b',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso2t',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso3',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
